backend:
  name: github
  branch: main 
  repo: SOFTROS-SISTEMAS/docs

# These lines should *not* be indented
media_folder: "static/img" # Media files will be stored in the repo under static/images/uploads
public_folder: "/img/" # The src attribute for uploaded media will begin with /images/uploads

collections:
- name: web
  label: "Web"
  folder: docs/web
  extension: md
  create: true
  slug: "{{slug}}"
  widget: "list"
  fields:
    - { name: title, label: Título, widget: string }
    - { name: body, label: Conteúdo, widget: markdown }
    - { name: slug, label: Arquivo, widget: string }
    - label: "Tags"
      name: "tags"
      widget: "list"
- name: mobile
  label: "Aplicativo"
  folder: docs/mobile
  extension: md
  create: true
  slug: "{{slug}}"
  widget: "list"
  fields:
    - { name: title, label: Título, widget: string }
    - { name: body, label: Conteúdo, widget: markdown }
    - { name: slug, label: Arquivo, widget: string }
    - label: "Tags"
      name: "tags"
      widget: "list"
- name: api
  label: "API"
  folder: docs/api
  extension: md
  create: true
  slug: "{{slug}}"
  widget: "list"
  fields:
    - { name: title, label: Título, widget: string }
    - { name: body, label: Conteúdo, widget: markdown }
    - { name: slug, label: Arquivo, widget: string }
    - label: "Tags"
      name: "tags"
      widget: "list"
      
